_wandb:
    value:
        cli_version: 0.22.0
        e:
            gglxc1ua8xr30yzb4pf4zqnb3xbmmt6n:
                args:
                    - --config
                    - configs/agent.yaml
                    - --motion_file
                    - /home/dhbaek/dh_workspace/data_phc/data/amass/valid_jh/amass_train.pkl
                    - --motion_ids
                    - 0-300
                    - --device
                    - auto
                    - --output_dir
                    - ./outputs/run_0_300
                codePath: scripts/train_vqvae.py
                codePathLocal: scripts/train_vqvae.py
                cpu_count: 24
                cpu_count_logical: 32
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "1965440720896"
                        used: "752779243520"
                email: romansabaek@gmail.com
                executable: /home/dhbaek/miniconda3/envs/vqvae/bin/python
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-cb00fcd2-33fd-f6d5-bcfa-e6168402595f
                host: zuldazar
                memory:
                    total: "67092926464"
                os: Linux-6.8.0-45-generic-x86_64-with-glibc2.35
                program: /home/dhbaek/dh_workspace/MotionVQVAE/scripts/train_vqvae.py
                python: CPython 3.10.18
                root: /home/dhbaek/dh_workspace/MotionVQVAE
                startedAt: "2025-10-02T20:33:06.709826Z"
                writerId: gglxc1ua8xr30yzb4pf4zqnb3xbmmt6n
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 53
            "2":
                - 1
                - 53
            "3":
                - 13
                - 15
                - 16
            "4": 3.10.18
            "5": 0.22.0
            "12": 0.22.0
            "13": linux-x86_64
batch_size:
    value: 256
beta:
    value: 1
code_dim:
    value: 512
commit:
    value: 0.02
depth:
    value: 3
device:
    value: cuda
dilation_growth_rate:
    value: 3
down_t:
    value: 2
gamma:
    value: 0.05
loss_vel:
    value: 0.5
lr:
    value: 0.0002
lr_scheduler:
    value:
        - 50000
        - 100000
motion_file:
    value: /home/dhbaek/dh_workspace/data_phc/data/amass/valid_jh/amass_train.pkl
motion_ids:
    value:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16
        - 17
        - 18
        - 19
        - 20
        - 21
        - 22
        - 23
        - 24
        - 25
        - 26
        - 27
        - 28
        - 29
        - 30
        - 31
        - 32
        - 33
        - 34
        - 35
        - 36
        - 37
        - 38
        - 39
        - 40
        - 41
        - 42
        - 43
        - 44
        - 45
        - 46
        - 47
        - 48
        - 49
        - 50
        - 51
        - 52
        - 53
        - 54
        - 55
        - 56
        - 57
        - 58
        - 59
        - 60
        - 61
        - 62
        - 63
        - 64
        - 65
        - 66
        - 67
        - 68
        - 69
        - 70
        - 71
        - 72
        - 73
        - 74
        - 75
        - 76
        - 77
        - 78
        - 79
        - 80
        - 81
        - 82
        - 83
        - 84
        - 85
        - 86
        - 87
        - 88
        - 89
        - 90
        - 91
        - 92
        - 93
        - 94
        - 95
        - 96
        - 97
        - 98
        - 99
        - 100
        - 101
        - 102
        - 103
        - 104
        - 105
        - 106
        - 107
        - 108
        - 109
        - 110
        - 111
        - 112
        - 113
        - 114
        - 115
        - 116
        - 117
        - 118
        - 119
        - 120
        - 121
        - 122
        - 123
        - 124
        - 125
        - 126
        - 127
        - 128
        - 129
        - 130
        - 131
        - 132
        - 133
        - 134
        - 135
        - 136
        - 137
        - 138
        - 139
        - 140
        - 141
        - 142
        - 143
        - 144
        - 145
        - 146
        - 147
        - 148
        - 149
        - 150
        - 151
        - 152
        - 153
        - 154
        - 155
        - 156
        - 157
        - 158
        - 159
        - 160
        - 161
        - 162
        - 163
        - 164
        - 165
        - 166
        - 167
        - 168
        - 169
        - 170
        - 171
        - 172
        - 173
        - 174
        - 175
        - 176
        - 177
        - 178
        - 179
        - 180
        - 181
        - 182
        - 183
        - 184
        - 185
        - 186
        - 187
        - 188
        - 189
        - 190
        - 191
        - 192
        - 193
        - 194
        - 195
        - 196
        - 197
        - 198
        - 199
        - 200
        - 201
        - 202
        - 203
        - 204
        - 205
        - 206
        - 207
        - 208
        - 209
        - 210
        - 211
        - 212
        - 213
        - 214
        - 215
        - 216
        - 217
        - 218
        - 219
        - 220
        - 221
        - 222
        - 223
        - 224
        - 225
        - 226
        - 227
        - 228
        - 229
        - 230
        - 231
        - 232
        - 233
        - 234
        - 235
        - 236
        - 237
        - 238
        - 239
        - 240
        - 241
        - 242
        - 243
        - 244
        - 245
        - 246
        - 247
        - 248
        - 249
        - 250
        - 251
        - 252
        - 253
        - 254
        - 255
        - 256
        - 257
        - 258
        - 259
        - 260
        - 261
        - 262
        - 263
        - 264
        - 265
        - 266
        - 267
        - 268
        - 269
        - 270
        - 271
        - 272
        - 273
        - 274
        - 275
        - 276
        - 277
        - 278
        - 279
        - 280
        - 281
        - 282
        - 283
        - 284
        - 285
        - 286
        - 287
        - 288
        - 289
        - 290
        - 291
        - 292
        - 293
        - 294
        - 295
        - 296
        - 297
        - 298
        - 299
        - 300
mu:
    value: 0.99
nb_code:
    value: 512
num_joints:
    value: 24
num_workers:
    value: 4
output_emb_width:
    value: 512
print_iter:
    value: 500
quantizer:
    value: ema_reset
recons_loss:
    value: l1_smooth
save_every:
    value: 1000
seed:
    value: 123
stride_t:
    value: 2
total_iter:
    value: 100000
use_wandb:
    value: true
vq_act:
    value: relu
vq_norm:
    value: null
wandb_project:
    value: amass-vqvae-mvq
wandb_run_name:
    value: ${wandb_run_name}
wandb_tags:
    value: []
warmup_iter:
    value: 1000
weight_decay:
    value: 0
width:
    value: 512
window_size:
    value: 32
